version: '3.7'
services:
    php:
        image: php:8.1-fpm
        volumes:
            - ./:/app
    nginx:
        image: nginx:latest
        ports:
            - 8123:8000
        volumes:
            - ./site.conf:/etc/nginx/conf.d/site.conf

